package com.chaosprotector.android

import com.android.build.api.variant.AndroidComponentsExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.net.URL
import java.util.Locale

/**
 * ChaosProtector Android Gradle Plugin.
 *
 * Automatically downloads the LLVM pass plugin for the host platform
 * and configures NDK builds to use it via -fpass-plugin.
 */
class ChaosProtectorPlugin : Plugin<Project> {

    companion object {
        const val EXTENSION_NAME = "chaosProtector"
        const val VERSION = "2.0.0"
        const val PLUGIN_DIR = ".chaosprotector"
    }

    override fun apply(project: Project) {
        val extension = project.extensions.create(
            EXTENSION_NAME,
            ChaosProtectorExtension::class.java
        )

        project.afterEvaluate {
            if (!extension.enabled.get()) return@afterEvaluate

            // Generate chaos-android.yml in the project root
            generateYamlConfig(project, extension)

            // Configure NDK to use the pass plugin
            configureNdkBuild(project, extension)
        }
    }

    private fun generateYamlConfig(project: Project, extension: ChaosProtectorExtension) {
        val configFile = project.file("chaos-android.yml")
        val p = extension.protections

        val yaml = buildString {
            appendLine("# Auto-generated by ChaosProtector Android Gradle Plugin v$VERSION")
            appendLine("# Do not edit manually - configure in build.gradle instead")
            appendLine()

            val licenseKey = extension.licenseKey.get()
            if (licenseKey.isNotEmpty()) {
                appendLine("license_key: $licenseKey")
                appendLine()
            }

            appendLine("protections:")
            appendLine("  string_encryption: ${p.stringEncryption.get()}")
            appendLine("  control_flow_flattening: ${p.controlFlowFlattening.get()}")
            appendLine("  opaque_constants: ${p.opaqueConstants.get()}")
            appendLine("  arithmetic: ${p.arithmetic.get()}")
            appendLine("  anti_hook: ${p.antiHook.get()}")
            appendLine("  indirect_branch: ${p.indirectBranch.get()}")
            appendLine("  indirect_call: ${p.indirectCall.get()}")
            appendLine("  break_control_flow: ${p.breakControlFlow.get()}")
            appendLine("  basic_block_duplicate: ${p.basicBlockDuplicate.get()}")
            appendLine("  function_outline: ${p.functionOutline.get()}")
            appendLine("  opaque_field_access: ${p.opaqueFieldAccess.get()}")
            appendLine()
            appendLine("exclude:")
            appendLine("  - \"JNI_OnLoad\"")
            appendLine("  - \"JNI_OnUnload\"")
        }

        configFile.writeText(yaml)
        project.logger.lifecycle("ChaosProtector: Generated chaos-android.yml")
    }

    private fun configureNdkBuild(project: Project, extension: ChaosProtectorExtension) {
        val pluginFile = ensurePluginDownloaded(project)
        if (pluginFile == null) {
            project.logger.error("ChaosProtector: Failed to locate pass plugin library")
            return
        }

        // For CMake-based NDK builds
        project.extensions.findByType(AndroidComponentsExtension::class.java)?.let { androidComponents ->
            androidComponents.onVariants { variant ->
                // Add -fpass-plugin flag to all native builds
                variant.externalNativeBuild?.let { nativeBuild ->
                    project.logger.lifecycle("ChaosProtector: Configuring variant ${variant.name}")
                }
            }
        }

        // Add to cmake arguments via android.defaultConfig.externalNativeBuild
        project.afterEvaluate {
            val cFlags = "-fpass-plugin=${pluginFile.absolutePath}"
            project.logger.lifecycle("ChaosProtector: Adding CFLAGS: $cFlags")

            // Write a cmake toolchain snippet that adds the flag
            val toolchainSnippet = project.file("$PLUGIN_DIR/chaos-toolchain.cmake")
            toolchainSnippet.parentFile.mkdirs()
            toolchainSnippet.writeText("""
                # ChaosProtector Android - auto-generated toolchain snippet
                # Include this in your CMakeLists.txt or pass as CMAKE_TOOLCHAIN_FILE
                set(CMAKE_C_FLAGS "${'$'}{CMAKE_C_FLAGS} -fpass-plugin=${pluginFile.absolutePath}")
                set(CMAKE_CXX_FLAGS "${'$'}{CMAKE_CXX_FLAGS} -fpass-plugin=${pluginFile.absolutePath}")
            """.trimIndent())

            project.logger.lifecycle("ChaosProtector: Toolchain snippet written to ${toolchainSnippet.path}")
            project.logger.lifecycle("ChaosProtector: Add to your CMakeLists.txt:")
            project.logger.lifecycle("  include(\${CMAKE_SOURCE_DIR}/$PLUGIN_DIR/chaos-toolchain.cmake)")
        }
    }

    private fun ensurePluginDownloaded(project: Project): File? {
        val pluginDir = File(project.rootDir, PLUGIN_DIR)
        pluginDir.mkdirs()

        val os = detectOS()
        val arch = detectArch()
        val libName = "libChaosAndroid.${if (os == "macos") "dylib" else "so"}"
        val pluginFile = File(pluginDir, libName)

        if (pluginFile.exists()) {
            project.logger.lifecycle("ChaosProtector: Using cached plugin at ${pluginFile.path}")
            return pluginFile
        }

        // Download from release server
        val downloadUrl = "https://chaosprotector.com/downloads/android/$VERSION/$os-$arch/$libName"
        project.logger.lifecycle("ChaosProtector: Downloading plugin from $downloadUrl")

        try {
            URL(downloadUrl).openStream().use { input ->
                pluginFile.outputStream().use { output ->
                    input.copyTo(output)
                }
            }
            pluginFile.setExecutable(true)
            project.logger.lifecycle("ChaosProtector: Plugin downloaded to ${pluginFile.path}")
            return pluginFile
        } catch (e: Exception) {
            project.logger.error("ChaosProtector: Failed to download plugin: ${e.message}")
            project.logger.error("ChaosProtector: Place libChaosAndroid.so manually in ${pluginDir.path}")
            return null
        }
    }

    private fun detectOS(): String {
        val os = System.getProperty("os.name").lowercase(Locale.ROOT)
        return when {
            os.contains("linux") -> "linux"
            os.contains("mac") || os.contains("darwin") -> "macos"
            os.contains("win") -> "windows"
            else -> "linux"
        }
    }

    private fun detectArch(): String {
        val arch = System.getProperty("os.arch").lowercase(Locale.ROOT)
        return when {
            arch.contains("aarch64") || arch.contains("arm64") -> "arm64"
            arch.contains("x86_64") || arch.contains("amd64") -> "x64"
            else -> "x64"
        }
    }
}
